# Generated by Django 4.1.7 on 2023-04-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('tagCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lista.tagreceita')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lista.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_in_receita', to='Lista.produto')),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lista.receita')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('promoTag', models.BooleanField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lista.produto')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lista.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('importancia', models.IntegerField()),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lista.lista')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod', to='Lista.produto')),
                ('produto_second_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondOption', to='Lista.produto')),
            ],
        ),
    ]
