# Generated by Django 4.1.7 on 2023-04-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0003_rename_productreceita_produtoreceita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_produto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto', to='Lista.produto'),
        ),
    ]
